<solution>
<>
<trains>[17;22;19;1;6]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[17;22;19;1;6]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;F;T;F;F;F;F]
<rails>[T;T;F;F;T;T]
</>
<>
<trains>[18;21;19;2;5]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;F;T;F;F;F;F]
<rails>[T;T;F;F;T;T]
</>
<>
<trains>[15;21;19;2;5]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;F;F;F;F;F;F]
<rails>[T;T;F;F;T;T]
</>
<>
<trains>[16;21;19;2;5]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;F;F;F;F;F;F]
<rails>[T;T;F;F;T;T]
</>
<>
<trains>[11;21;19;2;5]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;F;T;T]
</>
<>
<trains>[12;21;19;2;5]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;F;T;T]
</>
<>
<trains>[13;21;19;2;5]
<signals>[F;T;F;F;F;F;F;F;F;T;F;T;F;F;F;F;F;F;T;F;F;F]
<rails>[F;T;T;T;F;T]
</>
<>
<trains>[14;21;18;9;5]
<signals>[F;F;T;F;T;F;F;F;F;T;F;T;F;F;F;F;F;F;F;F;T;F]
<rails>[T;T;T;T;F;F]
</>
<>
<trains>[14;20;17;10;4]
<signals>[F;F;T;F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;F;T]
</>
<>
<trains>[21;19;17;11;3]
<signals>[F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;F;T]
</>
<>
<trains>[22;19;17;8;2]
<signals>[F;F;F;F;F;F;F;T;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F;T;T;F;T]
</>
<>
<trains>[22;19;17;5;2]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F;T;T;F;T]
</>
<>
<trains>[22;19;17;6;2]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F;T;T;F;T]
</>
<states> 14
<generated> 27
<time> 153.9948
</solution>
