<solution>
<>
<trains>[102;93;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[102;93;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;94;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;80;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;81;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;67;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;68;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;69;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;42;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;41;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;40;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;39;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;38;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;37;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;36;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;35;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;F;T]
</>
<>
<trains>[102;70;35;33;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;34;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;65;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;66;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;67;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;68;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;54;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;55;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;41;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;42;96]
<signals>[T;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;F;T]
</>
<>
<trains>[102;70;35;42;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;F;F;F]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[102;70;35;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;F;F;F]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[102;70;35;42;94]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;F;F;F]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[102;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;F;F;F]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[102;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[101;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[100;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[99;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[98;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[97;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[96;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[96;70;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;T;F]
</>
<>
<trains>[96;101;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;T;F]
</>
<>
<trains>[96;102;35;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;T;F]
</>
<>
<trains>[96;102;35;42;93]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F;T;F;T;F]
</>
<>
<trains>[96;102;34;42;93]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F;T;F;T;F]
</>
<>
<trains>[96;102;33;42;93]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F;T;F;T;F]
</>
<states> 44
<generated> 44
<time> 309.7237
</solution>
