<solution>
<>
<trains>[26;38;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;38;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[26;37;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[26;36;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[26;35;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[26;34;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[26;33;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[26;33;30]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;33;29]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;33;28]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;33;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;T]
</>
<>
<trains>[26;32;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;T]
</>
<>
<trains>[26;31;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;T]
</>
<>
<trains>[26;30;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;T]
</>
<>
<trains>[26;30;28]
<signals>[F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[27;30;28]
<signals>[F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[27;30;28]
<signals>[F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[15;30;28]
<signals>[F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[15;30;28]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[15;30;27]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[15;30;26]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[15;30;26]
<signals>[F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[16;30;26]
<signals>[F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[16;30;26]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[17;30;26]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[17;30;26]
<signals>[F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[18;30;26]
<signals>[F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[19;30;26]
<signals>[F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[19;30;26]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[33;30;26]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[34;30;26]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[35;30;26]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[36;30;26]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[37;30;26]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[38;30;26]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<states> 35
<generated> 49
<time> 193.2472
</solution>
