<solution>
<>
<trains>[60;79]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[60;79]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;78]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;77]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;76]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;75]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;74]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;73]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;72]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;71]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;70]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T]
<rails>[T;T]
</>
<>
<trains>[60;70]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;49]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;48]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;47]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;46]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;45]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;44]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;43]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;42]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;F]
</>
<>
<trains>[60;42]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[61;42]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[61;42]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[62;42]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[62;42]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[62;61]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[62;60]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[62;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[63;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[63;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[64;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[64;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[65;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[65;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[66;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[66;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[67;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[67;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[68;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[69;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[69;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[70;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[71;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[72;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[73;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[74;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[75;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[76;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[77;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[78;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[79;60]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<states> 51
<generated> 65
<time> 131.6736
</solution>
